version: '3'

services:
  db:
#    container_name: postgres-db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 54622307
      POSTGRES_DB: EcommerceTatuajes
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: